title: Axelweb
default_lang: fr
author:
  name: 'Axel Paillaud'
  email: contact@axelweb.fr
taxonomies:
  - category
  - tag
metadata:
  description: 'Axel, d√©veloppeur expert PrestaShop, modules et migrations'
  robots: 'noindex, nofollow'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
redirects: null
routes: null
blog:
  route: /blog
